### ISSUE TITLE
Your bird picture doesnt scale

### ISSUE THREAD

**Issue by dahnny012** [leewc/leewc.github.io#1]
When viewed through mobile/small resolutions the picture stretches across the screen abnormally.

**Comment by dahnny012** [comment]
When viewed through mobile/small resolutions the picture stretches across the screen abnormally.

**Comment by leewc** [comment]
Nice catch. Thanks. It's an issue that cropped up after merging a branch that has the theme updated to use SASS. instead of `width : auto` it should be `width : 100%` for `img` and the `featured` selectors. I also had to update the class names for layouts with sidebar else they don't scale and respond properly. Issue solved in commit ead168e4715741d14c1af5729476416578c89fdc.
